vertigo_case:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT') }}"
      dataset: "{{ env_var('GCP_DATASET') }}"
      threads: 4
      location: europe-west3
